# Generated by Django 5.1.1 on 2024-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
