# Generated by Django 5.1.1 on 2024-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0004_alter_pet_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10),
        ),
    ]
